name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      run: sudo apt-get install -q -y python3 python3-pip
    - name: Update Python setuptols module
      run: sudo python3 -m pip install -U setuptools
    - name: Install Python invoke module
      run: sudo python3 -m pip install -U invoke meson
    - name: Install Python meson module
      run: sudo python3 -m pip install -U meson
    - name: Setup Ninja
      run: sudo apt-get install -q -y ninja-build
    - name: Build
      run: inv build
    - name: Check
      run: inv check
  
